monitor_name = "eDP-1"
# external or mirror
default_external_mode = "extend"
open_bar_command = "waybar"
# close_bar_command = "killall waybar"
reload_bar_command = "sh /home/akashg/.scripts/launch-waybar"
suspend_command = "systemctl suspend"
lock_command = "swaylock"
utility_command = "playerctl --all-players -a pause"
get_monitors_command = "hyprctl monitors"
enable_internal_monitor_command = "hyprctl keyword monitor eDP-1,1920x1080,0x0,1"
disable_internal_monitor_command = "hyprctl keyword monitor eDP-1,disabled"
enable_external_monitor_command = "hyprctl keyword monitor ,highres,0x0,1"
disable_external_monitor_command = "hyprctl keyword monitor ,disabled"
extend_command = "hyprctl keyword monitor ,highres,1920x0,1"
mirror_command = "hyprctl keyword monitor ,highres,0x0,1"
wallpaper_command = "swaybg -m fill -i /home/akashg/.wallpapers/wall.png"
css_string = ""
