window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3


font:
  normal:
    family: "MesloLGS NF"
    style: Medium
  bold:
    family: "MesloLGS NF"
    style: Bold
  italic: 
    family: "MesloLGS NF"
    style: MediumItalic
  bold_italic:
    family: "MesloLGS NF"
    style: BoldItalic
  size: 12

window:
  opacity: 0.94

import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/theme.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml

